name: backbone
services:
  redis:
    image: redis
    networks:
      - backbone
    ports:
      - 6379:6379
  app:
    build:
      context: .
    networks:
      - backbone
    environment:
      API_ENABLED: 'true'
      WS_ENABLED: 'true'
      TCP_ENABLED: 'true'
      ADMIN_TOKEN: 'admin'
      JWT_SECRET: 'test'
      REDIS_ENABLED: 'true'
      REDIS_HOST: 'redis'
    ports:
      - 1883:1883
      - 8883:8883

networks:
  backbone:
