name: backbone
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  # app:
  #   build:
  #     context: .
  #   environment:
  #     HTTP_ENABLED: 'true'
  #     TCP_ENABLED: 'true'
  #     TOKEN_SECRET: 'test'
  #   ports:
  #     - 1883:1883
  #     - 8883:8883
